[package]
name = "rust-elrpc"
version = "0.1.0"
edition = "2021"
description = "Rust implementation of EPC (Emacs RPC) protocol"
license = "GPL-3.0-or-later"
keywords = ["emacs", "rpc", "epc", "s-expression"]
categories = ["network-programming"]

